name: Padavan Auto Build

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev gcc-multilib
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh          
    - name: Build Firmware
      env:
        TNAME: PSG1218_nano1
      run: |
        cd /opt/rt-n56u/trunk
        wget https://github.com/msl4437/padavan/raw/master/PSG1218_nano.config -O /opt/rt-n56u/trunk/configs/templates/PSG1218_nano1.config
        ./clear_tree
        fakeroot ./build_firmware_modify $TNAME
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
